security:
  firewalls:
    main:
      stateless: true
      custom_authenticators:
        - App\Security\Authenticator
  access_control:
    - { path: /validate$, roles: "PUBLIC_ACCESS" }
    - { path: /partner, roles: "ROLE_AUTHENTICATED" }
