security:
  firewalls:
    main:
      stateless: true
      custom_authenticators:
        - App\Security\FirebaseCookieAuthenticator
        - App\Security\SystemAuthenticator
  access_control:
    - { path: /public$, roles: "PUBLIC_ACCESS" }
    - { path: /validate$, roles: "PUBLIC_ACCESS" }
    - { path: /authenticated, roles: "ROLE_AUTHENTICATED" }
    - { path: /partner/approved, roles: ["ROLE_APPROVED"] }
    - { path: /admin, roles: "ROLE_ADMIN" }
    - { path: /system, roles: "ROLE_SYSTEM" }
