security:
  providers:
    app_user_provider:
      id: App\Security\UserProvider
  firewalls:
    main:
      custom_authenticators:
        - App\Security\Authenticator
  access_control:
    - { path: /validate$, roles: "PUBLIC_ACCESS" }
    - { path: .*, roles: "ROLE_AUTHENTICATED" }
