version: '3'

networks:
  default:
    name: traefik
    external: true

services:
  app:
    hostname: $COMPOSE_PROJECT_NAME
    image: ghcr.io/cords-connect/docker-container:debian-11.1.1.1
    volumes:
      - ./config/host/000-default.conf:/etc/apache2/sites-enabled/000-default.conf
      - ./config/host/envvars:/etc/apache2/envvars
      - .:/app
    command: /usr/sbin/apachectl -DFOREGROUND
    working_dir: /app
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.$COMPOSE_PROJECT_NAME.rule=Host(`$TRAEFIK_HOSTNAME`)
      - traefik.http.routers.$COMPOSE_PROJECT_NAME.tls=true
      - traefik.http.services.$COMPOSE_PROJECT_NAME.loadbalancer.server.port=80
