name: Call Deploy

on:
  workflow_dispatch:

  push:
    branches:
      - release/*

jobs:
  Call-DeployKit-Deploy:
    uses: Cords-Connect/DeployKit/.github/workflows/deploy.yml@main
    with:
      runner: host
      org_name: cords
