name: Deploy Dev

on:
  push:
    branches:
      - release/dev

jobs:
  Deploy-Dev:
    runs-on: backend-dev 
    env:
      ROUTERNAME: cords-partners-backend
      HOSTNAME: partners.backend.cords.dev
      CLIENT_HOSTNAME: partners.cords.dev
      APP_ENV: prod
      COOKIE_DOMAIN: .cords.dev
      APP_SECRET: ${{ secrets.APP_SECRET }}
      DATABASE_URL: mysql://root@partners_db:3306/partners?serverVersion=8.0&charset=utf8mb4
      CORS_ALLOW_ORIGIN: .*.cords.dev
      FIREBASE_SERVICE_URL: http://firebase-service:3000
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: ./tools/deploy /home/ubuntu/docker/cords-platform-api
