name: Deploy Dev

on:
  push:
    branches:
      - release/dev

jobs:
  Deploy:
    runs-on: backend-dev 
    env:
      ROUTERNAME: cords-partners-backend
      HOSTNAME: partners.backend.cords.dev
      CLIENT_HOSTNAME: partners.cords.dev
      APP_ENV: prod
      COOKIE_DOMAIN: .cords.dev
      APP_SECRET: ${{ secrets.APP_SECRET }}
      DATABASE_URL: mysql://root@partners_db:3306/partners?serverVersion=8.0&charset=utf8mb4
      CORS_ALLOW_ORIGIN: .*.cords.dev
      FIREBASE_SERVICE_URL: http://firebase-service:3000
      SENTRY_DSN: https://24ddf8367cdabdf6efa403dce1dfa187@o4504168857927680.ingest.us.sentry.io/4507124314734592
      ADMIN_EMAIL: akaats@findhelp.ca
      CORDS_ADMIN_FRONTEND_URL: admin.cords.dev
      FROM_EMAIL: noreply@cords.ai

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set environment variables
        run: |
          source ~/.secrets
          echo "SYSTEM_TOKEN=$SYSTEM_TOKEN" >> $GITHUB_ENV

      - run: ./tools/deploy /home/ubuntu/docker/cords-platform-api
