name: Release PR

on:
  push:
    branches:
      - release/prod

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v4
        with:
          token: ${{ secrets.BOT_TOKEN }}
          release-type: simple
          target-branch: release/prod
